openapi: 3.0.3
info:
  title: Simple Order API
  description: API for a simple hexagonal architecture order service.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /orders:
    post:
      summary: Create a new order
      operationId: createOrder
      tags:
        - orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
  /orders/{id}:
    get:
      summary: Get an order by ID
      operationId: getOrderById
      tags:
        - orders
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found

  /products:
    get:
      summary: Get a list of all products
      operationId: getProducts
      tags:
        - products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

components:
  schemas:
    CreateOrderRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
      required:
        - productId
        - quantity
    OrderResponse:
      type: object
      properties:
        orderId:
          type: string
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer
          format: int64
