spring:
    application:
        name: batch-manual-runner

    batch:
        job:
            enabled: true   # 자동 실행 OFF → ApplicationRunner에서 수동 실행
            name:  jobA
        jdbc:
            initialize-schema: always   # 개발·테스트 용도

    datasource:
        url: jdbc:mariadb://localhost:3306/BATCHDB?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
        username: orcmes           # 실제 계정
        password: P@ssw0rd         # 실제 비밀번호
        hikari:
            maximum-pool-size: 10        # 동시 Step 수에 맞춰 조정

#    datasource:
##        url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#        url: jdbc:h2:file:./data/batchdb;AUTO_SERVER=TRUE
#        driver-class-name: org.h2.Driver
#        username: sa       # 기본값
#        password:          # 기본은 빈 값
#    h2:
#        console:
#            enabled: true
#            path: /h2-console   # 원하는 경로로 변경 가능