openapi: 3.0.1
info:
  title: Intellian Device API
  description: Intellian 제품 정보를 관리하는 API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
paths:
  /intellian/devices:
    get:
      summary: 모든 Intellian 장비 목록 조회
      tags:
        - Intellian
      operationId: getIntellianDevices
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IntellianDevice'
components:
  schemas:
    IntellianDevice:
      type: object
      properties:
        serialNumber:
          type: string
        modelName:
          type: string
        firmwareVersion:
          type: string
        isActive:
          type: boolean
